---
title: "Transition indicator identification for chromatogram data"
author: "Deflandre Guillaume"
date: "2023-11-07"
output: html_document
---

# Data import and formatting

```{r read, echo = FALSE}

require(ggplot2)
require(plotly)
require(reshape2)
require(readxl)
require(tidyr)

  ###################
######## CHANGE #########

pat <- "276229-Run" 

######## CHANGE #########
  ###################


files <- dir("../clean/", pattern = pat, full.names = TRUE)

data_list <- list()

for (i in 1:4) { ## change 4 en 8 pour fichiers multiples
  file <- files[i]
  data <- read_xlsx(file)
  run_name <- paste("run", i, sep = "")
  data_list[[run_name]] <- data
}

com_run_list <- list()

for (i in 1:4) {
  com_run <- data_list[[i]]

  com_run_name <- paste("com_run", i, sep = "")
  assign(com_run_name, com_run)

  com_run_list[[i]] <- com_run
}


process_com_run <- function(com_run) {
  com_run <- com_run[-1, ]
  colnames(com_run) <- com_run[1, ]
  com_run <- com_run[-1, ]
  rownames(com_run) <- NULL
  phase_run <- com_run[1:8, c("cvv")]
  colnames(com_run)[1] <- "cv"
  colnames(com_run)[colnames(com_run) == "l/hour"] <- "flow"
  colnames(com_run)[colnames(com_run) == "mS/cm"] <- "cond"
  subcom_run <- com_run[, c("cv", "flow", "AU", "bar", "cond")]
  processed_data <- list(
    com_run = com_run,
    phase_run = phase_run,
    subcom_run = subcom_run
  )
  return(processed_data)
}

final <- list()

for (i in 1:4) {
  com_run_name <- paste("com_run", i, sep = "")
  processed_data <- process_com_run(get(com_run_name))
  final[[i]] <- processed_data
}

run1 = final[[1]]$subcom_run
run2 = final[[2]]$subcom_run
run3 = final[[3]]$subcom_run
run4 = final[[4]]$subcom_run


run1$cv = as.numeric(run1$cv)
run2$cv = as.numeric(run2$cv)
run3$cv = as.numeric(run3$cv)
run4$cv = as.numeric(run4$cv)

run1$bar = as.numeric(run1$bar)
run2$bar = as.numeric(run2$bar)
run3$bar = as.numeric(run3$bar)
run4$bar = as.numeric(run4$bar)

run1$AU = as.numeric(run1$AU)
run2$AU = as.numeric(run2$AU)
run3$AU = as.numeric(run3$AU)
run4$AU = as.numeric(run4$AU)

run1$flow = as.numeric(run1$flow)
run2$flow = as.numeric(run2$flow)
run3$flow = as.numeric(run3$flow)
run4$flow = as.numeric(run4$flow)

run1$cond = as.numeric(run1$cond)
run2$cond = as.numeric(run2$cond)
run3$cond = as.numeric(run3$cond)
run4$cond = as.numeric(run4$cond)

Log <- c("Set mark EQ1", "Set mark LOAD - phase 1","Set mark LOAD - phase 2", "Set mark EQ1","Set mark EL1","Set mark start_recolte","Set mark fin_recolte","Set mark REG1")

F1 = final[[1]]$phase_run
colnames(F1)[1] = "CV1"
F2 = final[[2]]$phase_run
colnames(F2)[1] = "CV2"
F3 = final[[3]]$phase_run
colnames(F3)[1] = "CV3"
F4 = final[[4]]$phase_run
colnames(F4)[1] = "CV4"

graphical = cbind(Log,F1,F2,F3,F4)

```

# Define Ranges

```{r ranges}

p <- ggplot(run1,aes(x = cv,y=cond))+
  geom_line(color = "black",linetype="solid")
ggplotly(p) # Use this to manually identify transition points

# ordre: CV_start, CV_end, CV_mid_theorique, 1 ou -1 pour montant ou descendant, 1/2/3/4 pour le parametre
cond_first_range <- c(0.1,4,1.07,1,1)
cond_scnd_range <- c(13,16.3,14.8,-1,1)
cond_third_range <-c(17,19.75,17.8,-1,1)
cond_fourth_range <-c(20.5,22,21.25,1,1)
cond_scnd_range_run4 <- c(13,15.3,14.1,-1,1)
cond_third_range_run4 <-c(16.5,18.75,17.1,-1,1)
cond_fourth_range_run4 <-c(19.5,21,20.5,1,1)

AU_first_range <- c(0,4,0.7,1,2) 
AU_scnd_range <- c(13.5,17.5,14.8,-1,2)
AU_third_range <-c(16.5,18.25,17.54,1,2)
AU_fourth_range <-c(18.2,21.6,19.2,-1,2)
AU_scnd_range_run4 <- c(12.5,16.7,14.1,-1,2)
AU_third_range_run4 <-c(15.5,17.25,16.85,1,2)
AU_fourth_range_run4 <-c(16.5,20.6,18.6,-1,2)


bar_first_range <- c(0.05,3,1.15,1,3)
bar_scnd_range <- c(12.5,17,14.5,-1,3)
bar_third_range <-c(16.5,17.7,16.86,1,3)
bar_fourth_range <- c(17.5,19.5,18.1,1,3)
bar_scnd_range_run4 <- c(12,15.8,13.1,-1,3)
bar_third_range_run4 <-c(15.1,17,16.2,1,3)
bar_fourth_range_run4 <- c(17,19.1,18.1,1,3)

flow_first_range <- c(13,16.5,13.8,-1,4)
flow_scnd_range <- c(15,19,18.3,-1,4)
flow_third_range <-c(19,22,20.01,1,4)
flow_first_range <- c(12,15.5,13.1,-1,4)
flow_scnd_range <- c(14,18,16.1,-1,4)
flow_third_range <-c(18,20.5,19.4,1,4)
```

# MAIN FUNCTION: Find plateaux and half-height point for each transition

**DO NOT TOUCH THIS FUNCTION !!!**
Except threshold value. That you may touch !

```{r FUNCTION}
### MAIN FUNCTION

the_magic_function <- function(data, which_range,run_trans,output){
  window <- as.data.frame(data[data$cv >= which_range[1] & data$cv <= which_range[2], ])
  window1 <- as.data.frame(data[data$cv >= which_range[1] & data$cv <= which_range[3], ])
  window2 <- as.data.frame(data[data$cv >= which_range[3] & data$cv <= which_range[2], ])
  
  h_value <- which(window$cv==window2$cv[1])
  
  UV1 <- window1$AU
  UV2 <- window2$AU  
  threshold <- 0.003
  plateau1 <- rep(0, length(UV1))
  plateau2 <- rep(0, length(UV2)) 
  
 if (which_range[4]==1){
  for (i in 11:(length(UV1) - 10)) { 
   delta_Y1 <- abs(UV1[i + 10] - UV1[i - 10])
   if (delta_Y1 <= threshold * UV1[i]) { plateau1[i] <- 1 }}
   
  for (i in 11:(length(UV2) - 10)) { 
   delta_Y2 <- abs(UV2[i + 10] - UV2[i - 10])
   if (delta_Y2 <= threshold * UV2[i]) { 
     plateau2[i] <- 1 
     }
  }  
 }

   if (which_range[4]==-1){
  for (i in 11:(length(UV1) - 10)) { 
   delta_Y1 <- abs(UV1[i - 10] - UV1[i + 10])
   if (delta_Y1 <= threshold * UV1[i]) { 
     plateau1[i] <- 1 
     }
  }
  for (i in 11:(length(UV2) - 10)) { 
   delta_Y2 <- abs(UV2[i - 10] - UV2[i + 10])
   if (delta_Y2 <= threshold * UV2[i]) { 
     plateau2[i] <- 1 
     }
  }  
 }
   
  
  if (which_range[5]==1){
    param <- "cond"
  }
  
  if (which_range[5]==2){
    param <- "AU"
  }
  
  if (which_range[5]==3){
    param <- "bar"
  }
  
  if (which_range[5]==4){
    param <- "flow"
  }
  
  indices1 <- which(plateau1 == 1)
  last_row1 <- tail(indices1, 1)
  first_row <- which(plateau2 == 1)[1]
  
  mid = abs((as.numeric(window[[param]][last_row1])-as.numeric(window[[param]][first_row+h_value]))/2)
  
  if (window[[param]][last_row1]<window[[param]][(first_row+h_value)]){half <- as.numeric(window[[param]][last_row1])+mid}
  if (window[[param]][last_row1]>window[[param]][(first_row+h_value)]){half <- as.numeric(window[[param]][(first_row+h_value)])+mid}
  
  diff_to_mid <- abs(window[[param]] - half)
  diff_to_mid <- diff_to_mid[!is.na(diff_to_mid)]
  halved <- as.numeric(which(diff_to_mid == min(diff_to_mid))[1])
  
gg <- ggplot(window, aes(x = cv, y = AU)) +
  geom_line(color = "black", linetype = "solid") +
  geom_hline(yintercept = window[[param]][last_row1], color = "lightgreen") +
  geom_hline(yintercept = window[[param]][first_row + h_value], color = "lightgreen") +
  geom_point(data = window[last_row1, ], aes(x = cv, y = AU), color = "red", size = 3) +
  geom_point(data = window[first_row + h_value, ], aes(x = cv, y = AU), color = "red", size = 3) +
  geom_point(data = window[halved, ], aes(x = cv, y = AU), color = "red", size = 3) +
  geom_text(data = window[last_row1, ], aes(label = AU), hjust = 0.5, vjust = -1, nudge_x = 0.1, nudge_y = 0.1) +
  geom_text(data = window[first_row + h_value, ], aes(label = AU), hjust = 0.5, vjust = -1, nudge_x = 0.1, nudge_y = 0.1) +
  geom_text(data = window[halved, ], aes(label = AU), hjust = 0.5, vjust = -1, nudge_x = 0.1, nudge_y = 0.1) +
  labs(title = "Selected Transition Range with plateau points")

# Calcul pente et valeurs:

  min_param <- window[[param]][last_row1]
  max_param <- window[[param]][first_row + h_value]
  min_cv <- window$cv[last_row1]
  max_cv <- window$cv[first_row + h_value]
  semi_param <- window[[param]][halved]
  semi_cv <- window$cv[halved]  
  
  num_values_above_below <- 15
  values <- window[(halved - num_values_above_below):(halved + num_values_above_below), ]
  
  y <- values[[param]]
  x <- values$cv
  fit <- lm(y ~ x)
  slope <- coef(fit)[2]
  intercept <- coef(fit)[1]
  lr <- paste(slope,"X","+","(",intercept,")",sep = " ")
  
  delta_cv_min <- abs(semi_cv-min_cv)
  delta_cv_max <- abs(semi_cv-max_cv)
  
  param_and_cv_values <- data.frame(param = c(min_param,semi_param,max_param),"cv" = c(min_cv,semi_cv,max_cv),"delta_CV&slope"=c(delta_cv_min,lr,delta_cv_max))
  
    row_order <- order(param_and_cv_values$cv)
    param_and_cv_values <- param_and_cv_values[row_order, ]

  colnames(param_and_cv_values) <- c(paste(param, run_trans,sep = "_"), paste("cv", run_trans,sep = "_"),paste("delta_CV&slope", run_trans,param,sep = "_"))
  rownames(param_and_cv_values) <- c("CV_start","CV_mid and slope","CV_end")
  
  if (output == "values") {
    return(param_and_cv_values)
    } 
  else if (output == "plot") {
    
    return(ggplotly(gg))
    } 
  else {
    stop("Invalid output format specified. Use 'dataframe' or 'ggplot'.")
  }
}

```

# Easier function in which the manual values are the inputs

```{r}

ucb <- function(run,param,cv1,cv2,run_trans){
  data <- as.data.frame(run[run$cv>=cv1&run$cv<=cv2,])
  l <- length(data[[param]])
  val1 <- data[[param]][1]
  val2 <- data[[param]][l]
  
  half <- (val1+val2)/2
  diff_to_mid <- abs(data[[param]] - half)
  diff_to_mid <- diff_to_mid[!is.na(diff_to_mid)]
  halved <- as.numeric(which(diff_to_mid == min(diff_to_mid))[1])
  
  half_param <- data[[param]][halved]
  half_cv <- data$cv[halved]
  
  num_values_above_below <- 3
  values <- data[(halved - num_values_above_below):(halved + num_values_above_below), ]
  
  y <- values[[param]]
  x <- values$cv
  fit <- lm(y ~ x)
  slope <- coef(fit)[2]
  
  delta_cv_min <- abs(half_cv-cv1)
  delta_cv_max <- abs(cv2-half_cv)
  
  table <- data.frame(param = c(val1,half_param,val2),"cv" = c(cv1,half_cv,cv2),"delta_CV&slope"=c(delta_cv_min,slope,delta_cv_max))
  
  colnames(table) <- c(paste(param, run_trans,sep = ""), paste("cv", run_trans,sep = ""),paste("delta_CV&slope", run_trans,param,sep = "_"))
  rownames(table) <- c("CV_start","CV_mid and slope","CV_end")
  
  return(table)
  
}
```

## Run that function

```{r}
ucb(run1,"bar",13.0264,13.3640,"run1_trans3")

```

# Apply the magic function, specify if you want the "values" or if you want to "plot"
```{r apply}
   
AU_run1_range1 <- the_magic_function(run1, AU_first_range, "run1_trans1", output = "values")
AU_run1_range2 <- the_magic_function(run1, AU_scnd_range, "run1_trans2", output = "values")
AU_run1_range3 <- the_magic_function(run1, AU_third_range, "run1_trans3", output = "values")
AU_run1_range4 <- the_magic_function(run1, AU_fourth_range, "run1_trans4", output = "values")

AU_run2_range1 <- the_magic_function(run2, AU_first_range, "run2_trans1", output = "values")
AU_run2_range2 <- the_magic_function(run2, AU_scnd_range, "run2_trans2", output = "values")
AU_run2_range3 <- the_magic_function(run2, AU_third_range, "run2_trans3", output = "values")
AU_run2_range4 <- the_magic_function(run2, AU_fourth_range, "run2_trans4", output = "values")

AU_run3_range1 <- the_magic_function(run3, AU_first_range, "run3_trans1", output = "values")
AU_run3_range2 <- the_magic_function(run3, AU_scnd_range, "run3_trans2", output = "values")
AU_run3_range3 <- the_magic_function(run3, AU_third_range, "run3_trans3", output = "values")
AU_run3_range4 <- the_magic_function(run3, AU_fourth_range, "run3_trans4", output = "values")

AU_run4_range1 <- the_magic_function(run4, AU_first_range, "run4_trans1", output = "values")
AU_run4_range2 <- the_magic_function(run4, AU_scnd_range_run4, "run4_trans2", output = "values")
AU_run4_range3 <- the_magic_function(run4, AU_third_range_run4, "run4_trans3", output = "values")
AU_run4_range4 <- the_magic_function(run4, AU_fourth_range_run4, "run4_trans4", output = "values")

bar_run1_range1 <- the_magic_function(run1, bar_first_range, "run1_trans1", output = "values")
bar_run1_range2 <- the_magic_function(run1, bar_scnd_range, "run1_trans2", output = "values")
bar_run1_range3 <- the_magic_function(run1, bar_third_range, "run1_trans3", output = "values")
bar_run1_range4 <- the_magic_function(run1, bar_fourth_range, "run1_trans4", output = "values")

bar_run2_range1 <- the_magic_function(run2, bar_first_range, "run2_trans1", output = "values")
bar_run2_range2 <- the_magic_function(run2, bar_scnd_range, "run2_trans2", output = "values")
bar_run2_range3 <- the_magic_function(run2, bar_third_range, "run2_trans3", output = "values")
bar_run2_range4 <- the_magic_function(run2, bar_fourth_range, "run2_trans4", output = "values")

bar_run3_range1 <- the_magic_function(run3, bar_first_range, "run3_trans1", output = "values")
bar_run3_range2 <- the_magic_function(run3, bar_scnd_range, "run3_trans2", output = "values")
bar_run3_range3 <- the_magic_function(run3, bar_third_range, "run3_trans3", output = "values")
bar_run3_range4 <- the_magic_function(run3, bar_fourth_range, "run3_trans4", output = "values")

bar_run4_range1 <- the_magic_function(run4, bar_first_range, "run4_trans1", output = "values")
bar_run4_range2 <- the_magic_function(run4, bar_scnd_range, "run4_trans2", output = "values")
bar_run4_range3 <- the_magic_function(run4, bar_third_range, "run4_trans3", output = "values")
bar_run4_range4 <- the_magic_function(run4, bar_fourth_range, "run4_trans4", output = "values")


flow_run1_range1 <- the_magic_function(run1, flow_first_range, "run1_trans1", output = "values")
flow_run1_range2 <- the_magic_function(run1, flow_scnd_range, "run1_trans2", output = "values")
flow_run1_range3 <- the_magic_function(run1, flow_third_range, "run1_trans3", output = "values")

flow_run2_range1 <- the_magic_function(run2, flow_first_range, "run2_trans1", output = "values")
flow_run2_range2 <- the_magic_function(run2, flow_scnd_range, "run2_trans2", output = "values")
flow_run2_range3 <- the_magic_function(run2, flow_third_range, "run2_trans3", output = "values")

flow_run3_range1 <- the_magic_function(run3, flow_first_range, "run3_trans1", output = "values")
flow_run3_range2 <- the_magic_function(run3, flow_scnd_range, "run3_trans2", output = "values")
flow_run3_range3 <- the_magic_function(run3, flow_third_range, "run3_trans3", output = "values")

flow_run4_range1 <- the_magic_function(run4, flow_first_range, "run4_trans1", output = "values")
flow_run4_range2 <- the_magic_function(run4, flow_scnd_range_run4, "run4_trans2", output = "values")
flow_run4_range3 <- the_magic_function(run4, flow_third_range_run4, "run4_trans3", output = "values")


cond_run1_range1 <- the_magic_function(run1, cond_first_range, "run1_trans1", output = "values")
cond_run1_range2 <- the_magic_function(run1, cond_scnd_range, "run1_trans2", output = "values")
cond_run1_range4 <- the_magic_function(run1, cond_fourth_range, "run1_trans4", output = "values")
cond_run1_range3 <- the_magic_function(run1, cond_third_range, "run1_trans3", output = "values")

cond_run2_range1 <- the_magic_function(run2, cond_first_range, "run2_trans1", output = "values")
cond_run2_range2 <- the_magic_function(run2, cond_scnd_range, "run2_trans2", output = "values")
cond_run2_range3 <- the_magic_function(run2, cond_third_range, "run2_trans3", output = "values")
cond_run2_range4 <- the_magic_function(run2, cond_fourth_range, "run2_trans4", output = "values")

cond_run3_range1 <- the_magic_function(run3, cond_first_range, "run3_trans1", output = "values")
cond_run3_range2 <- the_magic_function(run3, cond_scnd_range, "run3_trans2", output = "values")
cond_run3_range3 <- the_magic_function(run3, cond_third_range, "run3_trans3", output = "values")
cond_run3_range4 <- the_magic_function(run3, cond_fourth_range, "run3_trans4", output = "values")

cond_run4_range1 <- the_magic_function(run4, cond_first_range, "run4_trans1", output = "values")
cond_run4_range2 <- the_magic_function(run4, cond_scnd_range_run4, "run4_trans2", output = "values")
cond_run4_range3 <- the_magic_function(run4, cond_third_range_run4, "run4_trans3", output = "values")
cond_run4_range4 <- the_magic_function(run4, cond_fourth_range_run4, "run4_trans4", output = "values")



run1_param_and_cv <- cbind(run1_range1_AU,run1_range2_AU,run1_range3_AU,run1_range4_AU,un1_range1_cond,run1_range2_cond,run1_range3_cond,run1_range4_cond,un1_range1_bar,run1_range2_bar,run1_range3_bar,run1_range4_bar,un1_range1_flow,run1_range2_flow,run1_range3_flow)

run2_param_and_cv <- cbind(run2_range1_AU,run2_range2_AU,run2_range3_AU,run2_range4_AU,un2_range1_cond,run2_range2_cond,run2_range3_cond,run2_range4_cond,un2_range1_bar,run2_range2_bar,run2_range3_bar,run2_range4_bar,un2_range1_flow,run2_range2_flow,run2_range3_flow)

run3_param_and_cv <- cbind(run3_range1_AU,run3_range2_AU,run3_range3_AU,run3_range4_AU,un3_range1_cond,run3_range2_cond,run3_range3_cond,run3_range4_cond,un3_range1_bar,run3_range2_bar,run3_range3_bar,run3_range4_bar,un3_range1_flow,run3_range2_flow,run3_range3_flow)

run4_param_and_cv <- cbind(run4_range1_AU,run4_range2_AU,run4_range3_AU,run4_range4_AU,un4_range1_cond,run4_range2_cond,run4_range3_cond,run4_range4_cond,un4_range1_bar,run4_range2_bar,run4_range3_bar,run4_range4_bar,un4_range1_flow,run4_range2_flow,run4_range3_flow)

data_frames <- list(run1_param_and_cv, run2_param_and_cv, run3_param_and_cv, run4_param_and_cv)

reorder_columns_alphabetically <- function(df) {
  df[, order(names(df))]
}

data_frames <- lapply(data_frames, reorder_columns_alphabetically)

run1_param_and_cv <- data_frames[[1]]
run2_param_and_cv <- data_frames[[2]]
run3_param_and_cv <- data_frames[[3]]
run4_param_and_cv <- data_frames[[4]]
```

```{r}
alldata <- cbind(AU_run1_range1[3],AU_run1_range2[3],AU_run1_range3[3],AU_run1_range4[3],AU_run2_range1[3],AU_run2_range2[3],AU_run2_range3[3],AU_run2_range4[3],AU_run3_range1[3],AU_run3_range2[3],AU_run3_range3[3],AU_run3_range4[3],AU_run4_range1[3],AU_run4_range2[3],AU_run4_range3[3],AU_run4_range4[3])
```

# Print file

```{r manip, echo = FALSE}

num <- c(nrow(run1), nrow(run2), nrow(run3), nrow(run4))
print(num)
bibi <- data.frame(run1 = num[1], run2 = num[2], run3 = num[3], run4 = num[4])
bibi = as.matrix(bibi)

print(bibi)

col_order <- order(-bibi)
bibi <- bibi[, col_order]
bibi <- data.frame(bibi)

print(bibi)

diff1 <- bibi[1, ] - bibi[2, ]
diff2 <- bibi[1, ] - bibi[3, ]
diff3 <- bibi[1, ] - bibi[4, ]

diff = as.numeric(c(diff1,diff2,diff3))

# ajout de 0
fat <- rownames(bibi)[2:4]

position_to_insert=4000
row_with_zeros <- data.frame(cv = 0, flow = 0, AU = 0, bar = 0, cond = 0)


for (j in 1:3) {
  for (i in 1:diff[j]) {
    current_df <- get(fat[j])
    current_df <- rbind(current_df[1:position_to_insert, ], row_with_zeros, current_df[(position_to_insert+1):nrow(current_df), ])
    assign(fat[j], current_df)
    position_to_insert <- position_to_insert + 1
  }
}

num <- c(nrow(run1), nrow(run2), nrow(run3), nrow(run4))

require(openxlsx)

run2 <- run2[-1]
run3 <- run3[-1]
run4 <- run4[-1]


# Add the number 1 after every column name
colnames(run1) <- paste0(colnames(run1), "1")
colnames(run2) <- paste0(colnames(run2), "2")
colnames(run3) <- paste0(colnames(run3), "3")
colnames(run4) <- paste0(colnames(run4), "4")

finished_product1 <- cbind(run1, run2, run3, run4)
row_order1 <- order(finished_product1$cv1)
finished_product1$cv1[finished_product1$cv1 == 0] <- finished_product1$cv1[4000]
finished_product1$cv2[finished_product1$cv2 == 0] <- finished_product1$cv2[4000]
finished_product1$cv3[finished_product1$cv3 == 0] <- finished_product1$cv3[4000]
finished_product1$cv4[finished_product1$cv4 == 0] <- finished_product1$cv4[4000]

finished_product1 <- finished_product1[row_order1, ]
finished_product <- finished_product1

colnames(finished_product)[colnames(finished_product) == "cv1"] <- "cv"
finished_product$cv[finished_product$cv == 0] <- finished_product$cv[4000]

desired_order <- c("cv", paste0("AU", 1:4), paste0("bar", 1:4), paste0("cond", 1:4), paste0("flow", 1:4))
finished_product <- finished_product[, desired_order]

# desired_columns <- c("cv", "cond1", "cond2", "cond3", "cond4")
desired_columns <- c("cv", "AU1", "AU2", "AU3", "AU4")
# desired_columns <- c("cv", "bar1", "bar2", "bar3", "bar4")
# desired_columns <- c("cv", "flow1", "flow2", "flow3", "flow4")

filtered_data <- finished_product[, desired_columns]
filtered_data_long <- gather(filtered_data, param, value, -cv)
ggplot(data = filtered_data_long, aes(x = cv, y = value, color = param)) +
  geom_line() +
  labs(
    title = "Lineplot for the defined parameter",
    x = "cv",
    y = "Value"
  ) +
  theme_minimal()

wb <- createWorkbook()

addWorksheet(wb, sheetName = "All_Data")
writeData(wb, sheet = "All_Data", x = finished_product1)

addWorksheet(wb, sheetName = "Logbook and CV")
writeData(wb, sheet = "Logbook and CV", x = graphical)

addWorksheet(wb, sheetName = "run1_param")
writeData(wb, sheet = "run1_param", x = run1_param_and_cv, row.names = TRUE)

addWorksheet(wb, sheetName = "run2_param")
writeData(wb, sheet = "run2_param", x = run2_param_and_cv, row.names = TRUE)

addWorksheet(wb, sheetName = "run3_param")
writeData(wb, sheet = "run3_param", x = run3_param_and_cv, row.names = TRUE)

addWorksheet(wb, sheetName = "run4_param")
writeData(wb, sheet = "run4_param", x = run4_param_and_cv, row.names = TRUE)

addWorksheet(wb, sheetName = "AU values")
writeData(wb, sheet = "AU values", x = alldata)

saveWorkbook(wb, file = paste("finished_", pat, ".xlsx"), overwrite = TRUE)

```